### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by joseantoniosa** [picuino/tecno-recursos#2]
Please add compile instructions.
Thank you for your incredible work!

**Comment by joseantoniosa** [comment]
These commands don't work:

> cd tecno-recursos;  
> cp source/content.rst  source/conf.py   .
> make html
> cp ./source/_custom/templates/index.html  .


An error happened in rendering the page index.
Reason: TemplateNotFound('index.html')

**Comment by picuino** [comment]
**In Windows:**
Install CygWin64 in path \Bin\cygwin64
Install Python 3.9 in path \Bin\Python39
Install Miktex in path \Bin\Miktex\

execute _make-html-es-en.bat in base directory

**Comment by joseantoniosa** [comment]
Thank you. Now it works!
sphinx-build  -b html -D language="es" source _build/html/es
python source/_custom/sitemap.py "_build/html"
